# Generated by Django 2.0 on 2020-03-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_small',
            field=models.ImageField(null=True, upload_to='images/designers/main'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_two',
            field=models.ImageField(null=True, upload_to='images/designers/main'),
        ),
    ]
